file:
    - 'tests/functional/api/movies/index.js'
    - 'tests/functional/api/users/index.js'
    - 'tests/functional/api/popular/index.js'
    - 'tests/functional/api/genres/index.js'
    - 'tests/functional/api/Search/index.js'
    - 'tests/functional/api/upcoming/index.js'

require: '@babel/register'
exit: true
timeout: 4000
